language: rust

rust:
  - 1.33.0
  - 1.34.0
  - 1.35.0
  - 1.36.0
  - 1.37.0
  - stable
  - beta
  - nightly

before_script:
  - rustup component add clippy
script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo build
  - cargo test
